### ISSUE TITLE
Great work! - Can you license it under CC0 or similar?

### ISSUE THREAD

**Issue by SamuelMarks** [xorvoid/sectorc#2]
Enjoyed reading your blogpost and a bit jealous of the size you've gotten your compiler down to.

Was chatting with the guys in `#C` on LiberaChat (IRC) and they noted your lack of license. Have you considered [CC0](https://creativecommons.org/share-your-work/public-domain/cc0)?

PS: I'm working on [a C-to-C compiler (transpiler)](https://github.com/SamuelMarks/cdd-c) and getting myself in all kinds of knots (segfaults) with linked-lists, arrays, [non-null terminated UTF-8 strings](https://github.com/SamuelMarks/c-str-span) and combining macro parsing with C parsing (though [ROSE](https://en.wikipedia.org/wiki/ROSE_(compiler_framework)) can sortof do this it's not really open to outside contributors and is a pretty heavy tool for my needs). Would welcome your insights!

**Comment by xorvoid** [comment]
Happy to make it public domain. I did it only for fun and can't imagine it having any actual utility (vs other far superior solutions). If someone else does find utility, that would certainly make me proud.

**Comment by xorvoid** [comment]
Added Public Domain (CC0) license
